"""v2_add new column of title

Revision ID: 52577b7bebfa
Revises: abf1ea121462
Create Date: 2023-07-26 02:25:29.897104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52577b7bebfa'
down_revision = 'abf1ea121462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_title'), 'users', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_title'), table_name='users')
    op.drop_column('users', 'title')
    # ### end Alembic commands ###
